USE [INTEGRATION]
GO

CREATE TABLE [dbo].[TB_LYRICS_SEARCH](
	LYRIC_SEARCH	[NUMERIC]	(15, 0)		NOT NULL	IDENTITY	PRIMARY KEY,
	INSERTION_DATE	[DATETIME]				NOT NULL,
	AUTHOR			[VARCHAR]	(MAX)		NOT NULL,
	TITLE			[VARCHAR]	(MAX)		NOT NULL,
	VALID			[BIT]					NOT NULL
)